services:
  mySql-users-db:
    container_name: users-db
    image: mysql:8.0.33
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: users_db
    ports:
      - 8061:3306
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: